//! Shared GPU operation wrappers and kernel-crate re-exports.

mod attention;
pub mod call_spec;
#[cfg(feature = "kernel-call-trace")]
pub mod call_trace;
mod paged_plan;
#[cfg(feature = "kernel-call-trace")]
mod traced;

pub use attention::paged_attention_batch_decode_hd256_into;
pub use attention::paged_attention_batch_decode_into;
pub use attention::paged_attention_batch_decode_split_kv_into;
pub use attention::paged_attention_batch_decode_via_prefill_hd256_into;
pub use attention::prefill_attention_paged_into;
pub use paged_plan::PrefillPagedPlan;
pub use paged_plan::SplitKvCsr;
pub use paged_plan::build_split_kv_csr;
pub use pegainfer_kernels::ops::GEMM_LT_MAX_N;
pub use pegainfer_kernels::ops::Hd512DecodeMetadata;
pub use pegainfer_kernels::ops::LoraDecodeGroupedProjection;
pub use pegainfer_kernels::ops::SUPPORTED_GQA_GROUP_SIZES;
pub use pegainfer_kernels::ops::accumulate_bf16_token_scaled_to_f32_into;
pub use pegainfer_kernels::ops::add_batch;
pub use pegainfer_kernels::ops::add_batch_into;
pub use pegainfer_kernels::ops::argmax;
pub use pegainfer_kernels::ops::argmax_batch_bf16_into;
pub use pegainfer_kernels::ops::batch_prefill_paged_hd512_into;
pub use pegainfer_kernels::ops::batch_prefill_paged_window_hd256_into;
pub use pegainfer_kernels::ops::bf16_hidden_to_f32_into;
pub use pegainfer_kernels::ops::copy_hidden_rows_into;
pub use pegainfer_kernels::ops::copy_hidden_token_range_into;
pub use pegainfer_kernels::ops::dflash_qk_norm_rope_into;
pub use pegainfer_kernels::ops::eagle3_rope_into;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::embedding_batch;
pub use pegainfer_kernels::ops::embedding_decode_into;
pub use pegainfer_kernels::ops::extract_hidden_rows_raw_into;
pub use pegainfer_kernels::ops::extract_vec;
pub use pegainfer_kernels::ops::extract_vec_into;
pub use pegainfer_kernels::ops::extract_vec_ref;
pub use pegainfer_kernels::ops::extract_vec_ref_into;
pub use pegainfer_kernels::ops::f32_to_bf16_hidden_into;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::fused_add_rms_norm_batch_into;
pub use pegainfer_kernels::ops::fused_add_rms_norm_into;
pub use pegainfer_kernels::ops::gather_hidden_tokens_into;
pub use pegainfer_kernels::ops::gelu_tanh_mul_batch_into;
pub use pegainfer_kernels::ops::gemm;
pub use pegainfer_kernels::ops::gemm_graphsafe_into_checked;
pub use pegainfer_kernels::ops::gemm_graphsafe_ref_into_checked;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::gemm_into;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::gemm_into_checked;
pub use pegainfer_kernels::ops::gemm_lt_tune;
pub use pegainfer_kernels::ops::gemm_per_token;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::gemm_rows_into;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::gemm_rows_into_checked;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::gemm_token_range_into_checked;
pub use pegainfer_kernels::ops::gemv;
pub use pegainfer_kernels::ops::linear;
pub use pegainfer_kernels::ops::lora_decode_fused_delta_group3_into;
pub use pegainfer_kernels::ops::lora_decode_fused_delta_into;
pub use pegainfer_kernels::ops::pack_lora_b_rows_into;
pub use pegainfer_kernels::ops::paged_attention_batch_decode_split_kv_hd512_into;
pub use pegainfer_kernels::ops::qk_norm_partial_rope_batched_decode_hd256_into;
pub use pegainfer_kernels::ops::qk_norm_partial_rope_batched_decode_hd512_into;
pub use pegainfer_kernels::ops::qk_norm_partial_rope_paged_decode_hd512_into;
pub use pegainfer_kernels::ops::qk_norm_partial_rope_paged_prefill_hd512_into;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::qk_norm_rope_batch_decode_into;
pub use pegainfer_kernels::ops::qk_norm_rope_prefill_hd256_plain_into;
pub use pegainfer_kernels::ops::qkv_norm_rope_paged_decode_hd256_plain_into;
pub use pegainfer_kernels::ops::qkv_norm_rope_paged_prefill_hd256_plain_into;
pub use pegainfer_kernels::ops::rms_norm;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::rms_norm_batch_into;
pub use pegainfer_kernels::ops::rms_norm_batch_offset_into;
pub use pegainfer_kernels::ops::rms_norm_gated_batch_into;
pub use pegainfer_kernels::ops::rms_norm_into;
pub use pegainfer_kernels::ops::rms_norm_offset_into;
pub use pegainfer_kernels::ops::scale_bf16_in_place;
pub use pegainfer_kernels::ops::scale_f32_in_place;
pub use pegainfer_kernels::ops::scaled_add_batch_into;
pub use pegainfer_kernels::ops::scaled_add_rows_indexed_into;
pub use pegainfer_kernels::ops::scaled_add_rows_into;
pub use pegainfer_kernels::ops::scaled_add_rows_token_range_into;
pub use pegainfer_kernels::ops::silu_mul_batch;
pub use pegainfer_kernels::ops::silu_mul_batch_into;
#[cfg(not(feature = "kernel-call-trace"))]
pub use pegainfer_kernels::ops::silu_mul_fused_batch_into;
pub use pegainfer_kernels::ops::single_decode_nhd_into;
pub use pegainfer_kernels::ops::single_prefill_hd256_into;
pub use pegainfer_kernels::ops::single_prefill_hd512_into;
pub use pegainfer_kernels::ops::single_prefill_nhd_causal_into;
pub use pegainfer_kernels::ops::single_prefill_nhd_noncausal_into;
pub use pegainfer_kernels::ops::softcap_bf16_in_place;
pub use pegainfer_kernels::ops::write_vec_into;
#[cfg(feature = "kernel-call-trace")]
pub use traced::embedding_batch;
#[cfg(feature = "kernel-call-trace")]
pub use traced::fused_add_rms_norm_batch_into;
#[cfg(feature = "kernel-call-trace")]
pub use traced::gemm_into;
#[cfg(feature = "kernel-call-trace")]
pub use traced::gemm_into_checked;
#[cfg(feature = "kernel-call-trace")]
pub use traced::gemm_rows_into;
#[cfg(feature = "kernel-call-trace")]
pub use traced::gemm_rows_into_checked;
#[cfg(feature = "kernel-call-trace")]
pub use traced::gemm_token_range_into_checked;
#[cfg(feature = "kernel-call-trace")]
pub use traced::qk_norm_rope_batch_decode_into;
#[cfg(feature = "kernel-call-trace")]
pub use traced::rms_norm_batch_into;
#[cfg(feature = "kernel-call-trace")]
pub use traced::silu_mul_fused_batch_into;
